name: 🎮 Gameplay Change
description: Submit your suggestions to improve an existing map on Warzone.
title: '[Gameplay] '
labels:
  - map
  - gameplay
body:
  - type: input
    id: map-name
    attributes:
      label: Map Name
      placeholder: 'Example: Acromion'
    validations:
      required: true
  - type: textarea
    id: map-suggestion
    attributes:
      label: Suggestion
      description: >-
        Be descriptive! It helps us determine how we can best improve an
        existing map for everyone.
      placeholder: >-
        Example: The islands on this map is too small for the team size.
        Increase the size of the island or reduce the team size.
    validations:
      required: true
  - type: textarea
    id: map-gameplay-context
    attributes:
      label: Screenshots or Videos (if applicable)
      description: >-
        You may use image hosting services, such as [Imgur](https://imgur.com/), for screenshots. You
        can also use [YouTube](https://www.youtube.com/) or [Streamable](https://streamable.com/) for video hosting.